/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SupertoneError } from "./supertoneerror.js";

export type BadRequestErrorResponseData = {
  /**
   * Response status
   */
  status: string;
  /**
   * Bad request error message
   */
  message: string;
};

export class BadRequestErrorResponse extends SupertoneError {
  /**
   * Response status
   */
  status: string;

  /** The original data that was passed to this error instance. */
  data$: BadRequestErrorResponseData;

  constructor(
    err: BadRequestErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;

    this.name = "BadRequestErrorResponse";
  }
}

/** @internal */
export const BadRequestErrorResponse$inboundSchema: z.ZodType<
  BadRequestErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new BadRequestErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type BadRequestErrorResponse$Outbound = {
  status: string;
  message: string;
};

/** @internal */
export const BadRequestErrorResponse$outboundSchema: z.ZodType<
  BadRequestErrorResponse$Outbound,
  z.ZodTypeDef,
  BadRequestErrorResponse
> = z.instanceof(BadRequestErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    status: z.string(),
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BadRequestErrorResponse$ {
  /** @deprecated use `BadRequestErrorResponse$inboundSchema` instead. */
  export const inboundSchema = BadRequestErrorResponse$inboundSchema;
  /** @deprecated use `BadRequestErrorResponse$outboundSchema` instead. */
  export const outboundSchema = BadRequestErrorResponse$outboundSchema;
  /** @deprecated use `BadRequestErrorResponse$Outbound` instead. */
  export type Outbound = BadRequestErrorResponse$Outbound;
}
