/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { SupertoneError } from "./supertoneerror.js";

export type ForbiddenErrorResponseData = {
  /**
   * Response status
   */
  status: string;
  /**
   * Forbidden error details
   */
  message: models.ForbiddenErrorResponseMessage;
};

export class ForbiddenErrorResponse extends SupertoneError {
  /**
   * Response status
   */
  status: string;

  /** The original data that was passed to this error instance. */
  data$: ForbiddenErrorResponseData;

  constructor(
    err: ForbiddenErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;

    this.name = "ForbiddenErrorResponse";
  }
}

/** @internal */
export const ForbiddenErrorResponse$inboundSchema: z.ZodType<
  ForbiddenErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  message: z.lazy(() => models.ForbiddenErrorResponseMessage$inboundSchema),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ForbiddenErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ForbiddenErrorResponse$Outbound = {
  status: string;
  message: models.ForbiddenErrorResponseMessage$Outbound;
};

/** @internal */
export const ForbiddenErrorResponse$outboundSchema: z.ZodType<
  ForbiddenErrorResponse$Outbound,
  z.ZodTypeDef,
  ForbiddenErrorResponse
> = z.instanceof(ForbiddenErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    status: z.string(),
    message: z.lazy(() => models.ForbiddenErrorResponseMessage$outboundSchema),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ForbiddenErrorResponse$ {
  /** @deprecated use `ForbiddenErrorResponse$inboundSchema` instead. */
  export const inboundSchema = ForbiddenErrorResponse$inboundSchema;
  /** @deprecated use `ForbiddenErrorResponse$outboundSchema` instead. */
  export const outboundSchema = ForbiddenErrorResponse$outboundSchema;
  /** @deprecated use `ForbiddenErrorResponse$Outbound` instead. */
  export type Outbound = ForbiddenErrorResponse$Outbound;
}
