/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as models from "../index.js";
import { SupertoneError } from "./supertoneerror.js";

export type RequestTimeoutErrorResponseData = {
  /**
   * Response status
   */
  status: string;
  /**
   * Request timeout error details
   */
  message: models.RequestTimeoutErrorResponseMessage;
};

export class RequestTimeoutErrorResponse extends SupertoneError {
  /**
   * Response status
   */
  status: string;

  /** The original data that was passed to this error instance. */
  data$: RequestTimeoutErrorResponseData;

  constructor(
    err: RequestTimeoutErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;

    this.name = "RequestTimeoutErrorResponse";
  }
}

/** @internal */
export const RequestTimeoutErrorResponse$inboundSchema: z.ZodType<
  RequestTimeoutErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  message: z.lazy(() =>
    models.RequestTimeoutErrorResponseMessage$inboundSchema
  ),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new RequestTimeoutErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type RequestTimeoutErrorResponse$Outbound = {
  status: string;
  message: models.RequestTimeoutErrorResponseMessage$Outbound;
};

/** @internal */
export const RequestTimeoutErrorResponse$outboundSchema: z.ZodType<
  RequestTimeoutErrorResponse$Outbound,
  z.ZodTypeDef,
  RequestTimeoutErrorResponse
> = z.instanceof(RequestTimeoutErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    status: z.string(),
    message: z.lazy(() =>
      models.RequestTimeoutErrorResponseMessage$outboundSchema
    ),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RequestTimeoutErrorResponse$ {
  /** @deprecated use `RequestTimeoutErrorResponse$inboundSchema` instead. */
  export const inboundSchema = RequestTimeoutErrorResponse$inboundSchema;
  /** @deprecated use `RequestTimeoutErrorResponse$outboundSchema` instead. */
  export const outboundSchema = RequestTimeoutErrorResponse$outboundSchema;
  /** @deprecated use `RequestTimeoutErrorResponse$Outbound` instead. */
  export type Outbound = RequestTimeoutErrorResponse$Outbound;
}
