/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SupertoneError } from "./supertoneerror.js";

export type UnsupportedMediaTypeErrorResponseData = {
  /**
   * Response status
   */
  status: string;
  /**
   * Unsupported media type error message
   */
  message: string;
};

export class UnsupportedMediaTypeErrorResponse extends SupertoneError {
  /**
   * Response status
   */
  status: string;

  /** The original data that was passed to this error instance. */
  data$: UnsupportedMediaTypeErrorResponseData;

  constructor(
    err: UnsupportedMediaTypeErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.status = err.status;

    this.name = "UnsupportedMediaTypeErrorResponse";
  }
}

/** @internal */
export const UnsupportedMediaTypeErrorResponse$inboundSchema: z.ZodType<
  UnsupportedMediaTypeErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new UnsupportedMediaTypeErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type UnsupportedMediaTypeErrorResponse$Outbound = {
  status: string;
  message: string;
};

/** @internal */
export const UnsupportedMediaTypeErrorResponse$outboundSchema: z.ZodType<
  UnsupportedMediaTypeErrorResponse$Outbound,
  z.ZodTypeDef,
  UnsupportedMediaTypeErrorResponse
> = z.instanceof(UnsupportedMediaTypeErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    status: z.string(),
    message: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnsupportedMediaTypeErrorResponse$ {
  /** @deprecated use `UnsupportedMediaTypeErrorResponse$inboundSchema` instead. */
  export const inboundSchema = UnsupportedMediaTypeErrorResponse$inboundSchema;
  /** @deprecated use `UnsupportedMediaTypeErrorResponse$outboundSchema` instead. */
  export const outboundSchema =
    UnsupportedMediaTypeErrorResponse$outboundSchema;
  /** @deprecated use `UnsupportedMediaTypeErrorResponse$Outbound` instead. */
  export type Outbound = UnsupportedMediaTypeErrorResponse$Outbound;
}
