/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { CustomVoices } from "./customvoices.js";
import { TextToSpeech } from "./texttospeech.js";
import { Usage } from "./usage.js";
import { Voices } from "./voices.js";

export class Supertone extends ClientSDK {
  private _textToSpeech?: TextToSpeech;
  get textToSpeech(): TextToSpeech {
    return (this._textToSpeech ??= new TextToSpeech(this._options));
  }

  private _voices?: Voices;
  get voices(): Voices {
    return (this._voices ??= new Voices(this._options));
  }

  private _customVoices?: CustomVoices;
  get customVoices(): CustomVoices {
    return (this._customVoices ??= new CustomVoices(this._options));
  }

  private _usage?: Usage;
  get usage(): Usage {
    return (this._usage ??= new Usage(this._options));
  }
}
