/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usageGetCreditBalance } from "../funcs/usageGetCreditBalance.js";
import { usageGetUsage } from "../funcs/usageGetUsage.js";
import { usageGetVoiceUsage } from "../funcs/usageGetVoiceUsage.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Usage extends ClientSDK {
  /**
   * Retrieve TTS API usage data
   *
   * @remarks
   * Retrieves a list of all TTS API usage records filtered by a specified date range. All dates are in UTC+0 timezone.
   */
  async getVoiceUsage(
    request: operations.GetVoiceUsageRequest,
    options?: RequestOptions,
  ): Promise<models.GetUsageListV1Response> {
    return unwrapAsync(usageGetVoiceUsage(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve advanced API usage analytics
   *
   * @remarks
   * Retrieves API usage data with advanced features including time bucketing, multi-dimensional breakdowns, and pagination. All timestamps should be in RFC3339 format.
   */
  async getUsage(
    request: operations.GetUsageRequest,
    options?: RequestOptions,
  ): Promise<models.UsageAnalyticsResponse> {
    return unwrapAsync(usageGetUsage(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve credit balance
   *
   * @remarks
   * Retrieves credit balance of the user.
   */
  async getCreditBalance(
    options?: RequestOptions,
  ): Promise<models.GetCreditBalanceResponse> {
    return unwrapAsync(usageGetCreditBalance(
      this,
      options,
    ));
  }
}
