/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voicesGetVoice } from "../funcs/voicesGetVoice.js";
import { voicesListVoices } from "../funcs/voicesListVoices.js";
import { voicesSearchVoices } from "../funcs/voicesSearchVoices.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Voices extends ClientSDK {
  /**
   * Gets available voices
   *
   * @remarks
   * Gets a paginated list of voices available to the user based on internal group logic, using token-based pagination.
   */
  async listVoices(
    request?: operations.ListVoicesRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.GetAPICharacterListResponse> {
    return unwrapAsync(voicesListVoices(
      this,
      request,
      options,
    ));
  }

  /**
   * Search voices.
   *
   * @remarks
   * Search and filter voices based on various parameters.
   */
  async searchVoices(
    request?: operations.SearchVoicesRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.GetAPICharacterListResponse> {
    return unwrapAsync(voicesSearchVoices(
      this,
      request,
      options,
    ));
  }

  /**
   * Get voice details by ID
   *
   * @remarks
   * Gets detailed information about a specific voice by its voice ID. Only supports preset voices.
   */
  async getVoice(
    request: operations.GetVoiceRequest,
    options?: RequestOptions,
  ): Promise<models.GetCharacterByIdResponse> {
    return unwrapAsync(voicesGetVoice(
      this,
      request,
      options,
    ));
  }
}
