/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteCustomVoiceRequest = {
  voiceId: string;
};

/** @internal */
export const DeleteCustomVoiceRequest$inboundSchema: z.ZodType<
  DeleteCustomVoiceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  voice_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "voice_id": "voiceId",
  });
});

/** @internal */
export type DeleteCustomVoiceRequest$Outbound = {
  voice_id: string;
};

/** @internal */
export const DeleteCustomVoiceRequest$outboundSchema: z.ZodType<
  DeleteCustomVoiceRequest$Outbound,
  z.ZodTypeDef,
  DeleteCustomVoiceRequest
> = z.object({
  voiceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    voiceId: "voice_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteCustomVoiceRequest$ {
  /** @deprecated use `DeleteCustomVoiceRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteCustomVoiceRequest$inboundSchema;
  /** @deprecated use `DeleteCustomVoiceRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteCustomVoiceRequest$outboundSchema;
  /** @deprecated use `DeleteCustomVoiceRequest$Outbound` instead. */
  export type Outbound = DeleteCustomVoiceRequest$Outbound;
}

export function deleteCustomVoiceRequestToJSON(
  deleteCustomVoiceRequest: DeleteCustomVoiceRequest,
): string {
  return JSON.stringify(
    DeleteCustomVoiceRequest$outboundSchema.parse(deleteCustomVoiceRequest),
  );
}

export function deleteCustomVoiceRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteCustomVoiceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteCustomVoiceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteCustomVoiceRequest' from JSON`,
  );
}
