/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type EditCustomVoiceRequest = {
  voiceId: string;
  updateClonedVoiceRequest: models.UpdateClonedVoiceRequest;
};

/** @internal */
export const EditCustomVoiceRequest$inboundSchema: z.ZodType<
  EditCustomVoiceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  voice_id: z.string(),
  UpdateClonedVoiceRequest: models.UpdateClonedVoiceRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "voice_id": "voiceId",
    "UpdateClonedVoiceRequest": "updateClonedVoiceRequest",
  });
});

/** @internal */
export type EditCustomVoiceRequest$Outbound = {
  voice_id: string;
  UpdateClonedVoiceRequest: models.UpdateClonedVoiceRequest$Outbound;
};

/** @internal */
export const EditCustomVoiceRequest$outboundSchema: z.ZodType<
  EditCustomVoiceRequest$Outbound,
  z.ZodTypeDef,
  EditCustomVoiceRequest
> = z.object({
  voiceId: z.string(),
  updateClonedVoiceRequest: models.UpdateClonedVoiceRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    voiceId: "voice_id",
    updateClonedVoiceRequest: "UpdateClonedVoiceRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EditCustomVoiceRequest$ {
  /** @deprecated use `EditCustomVoiceRequest$inboundSchema` instead. */
  export const inboundSchema = EditCustomVoiceRequest$inboundSchema;
  /** @deprecated use `EditCustomVoiceRequest$outboundSchema` instead. */
  export const outboundSchema = EditCustomVoiceRequest$outboundSchema;
  /** @deprecated use `EditCustomVoiceRequest$Outbound` instead. */
  export type Outbound = EditCustomVoiceRequest$Outbound;
}

export function editCustomVoiceRequestToJSON(
  editCustomVoiceRequest: EditCustomVoiceRequest,
): string {
  return JSON.stringify(
    EditCustomVoiceRequest$outboundSchema.parse(editCustomVoiceRequest),
  );
}

export function editCustomVoiceRequestFromJSON(
  jsonString: string,
): SafeParseResult<EditCustomVoiceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EditCustomVoiceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EditCustomVoiceRequest' from JSON`,
  );
}
