/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetVoiceUsageRequest = {
  /**
   * The start date in YYYY-MM-DD format.
   */
  startDate: string;
  /**
   * The end date in YYYY-MM-DD format.
   */
  endDate: string;
};

/** @internal */
export const GetVoiceUsageRequest$inboundSchema: z.ZodType<
  GetVoiceUsageRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  start_date: z.string(),
  end_date: z.string(),
}).transform((v) => {
  return remap$(v, {
    "start_date": "startDate",
    "end_date": "endDate",
  });
});

/** @internal */
export type GetVoiceUsageRequest$Outbound = {
  start_date: string;
  end_date: string;
};

/** @internal */
export const GetVoiceUsageRequest$outboundSchema: z.ZodType<
  GetVoiceUsageRequest$Outbound,
  z.ZodTypeDef,
  GetVoiceUsageRequest
> = z.object({
  startDate: z.string(),
  endDate: z.string(),
}).transform((v) => {
  return remap$(v, {
    startDate: "start_date",
    endDate: "end_date",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetVoiceUsageRequest$ {
  /** @deprecated use `GetVoiceUsageRequest$inboundSchema` instead. */
  export const inboundSchema = GetVoiceUsageRequest$inboundSchema;
  /** @deprecated use `GetVoiceUsageRequest$outboundSchema` instead. */
  export const outboundSchema = GetVoiceUsageRequest$outboundSchema;
  /** @deprecated use `GetVoiceUsageRequest$Outbound` instead. */
  export type Outbound = GetVoiceUsageRequest$Outbound;
}

export function getVoiceUsageRequestToJSON(
  getVoiceUsageRequest: GetVoiceUsageRequest,
): string {
  return JSON.stringify(
    GetVoiceUsageRequest$outboundSchema.parse(getVoiceUsageRequest),
  );
}

export function getVoiceUsageRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetVoiceUsageRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetVoiceUsageRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetVoiceUsageRequest' from JSON`,
  );
}
