/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListVoicesRequest = {
  /**
   * Number of items per page (default: 20, min: 10, max: 100)
   */
  pageSize?: number | undefined;
  /**
   * Token for pagination (obtained from the previous page's response)
   */
  nextPageToken?: string | undefined;
};

/** @internal */
export const ListVoicesRequest$inboundSchema: z.ZodType<
  ListVoicesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page_size: z.number().optional(),
  next_page_token: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "page_size": "pageSize",
    "next_page_token": "nextPageToken",
  });
});

/** @internal */
export type ListVoicesRequest$Outbound = {
  page_size?: number | undefined;
  next_page_token?: string | undefined;
};

/** @internal */
export const ListVoicesRequest$outboundSchema: z.ZodType<
  ListVoicesRequest$Outbound,
  z.ZodTypeDef,
  ListVoicesRequest
> = z.object({
  pageSize: z.number().optional(),
  nextPageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page_size",
    nextPageToken: "next_page_token",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListVoicesRequest$ {
  /** @deprecated use `ListVoicesRequest$inboundSchema` instead. */
  export const inboundSchema = ListVoicesRequest$inboundSchema;
  /** @deprecated use `ListVoicesRequest$outboundSchema` instead. */
  export const outboundSchema = ListVoicesRequest$outboundSchema;
  /** @deprecated use `ListVoicesRequest$Outbound` instead. */
  export type Outbound = ListVoicesRequest$Outbound;
}

export function listVoicesRequestToJSON(
  listVoicesRequest: ListVoicesRequest,
): string {
  return JSON.stringify(
    ListVoicesRequest$outboundSchema.parse(listVoicesRequest),
  );
}

export function listVoicesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListVoicesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListVoicesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListVoicesRequest' from JSON`,
  );
}
