/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PredictDurationRequest = {
  voiceId: string;
  predictTTSDurationRequest: models.PredictTTSDurationRequest;
};

/**
 * Returns predicted duration of the audio in seconds
 */
export type PredictDurationResponse = {
  duration?: number | undefined;
};

/** @internal */
export const PredictDurationRequest$inboundSchema: z.ZodType<
  PredictDurationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  voice_id: z.string(),
  PredictTTSDurationRequest: models.PredictTTSDurationRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "voice_id": "voiceId",
    "PredictTTSDurationRequest": "predictTTSDurationRequest",
  });
});

/** @internal */
export type PredictDurationRequest$Outbound = {
  voice_id: string;
  PredictTTSDurationRequest: models.PredictTTSDurationRequest$Outbound;
};

/** @internal */
export const PredictDurationRequest$outboundSchema: z.ZodType<
  PredictDurationRequest$Outbound,
  z.ZodTypeDef,
  PredictDurationRequest
> = z.object({
  voiceId: z.string(),
  predictTTSDurationRequest: models.PredictTTSDurationRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    voiceId: "voice_id",
    predictTTSDurationRequest: "PredictTTSDurationRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PredictDurationRequest$ {
  /** @deprecated use `PredictDurationRequest$inboundSchema` instead. */
  export const inboundSchema = PredictDurationRequest$inboundSchema;
  /** @deprecated use `PredictDurationRequest$outboundSchema` instead. */
  export const outboundSchema = PredictDurationRequest$outboundSchema;
  /** @deprecated use `PredictDurationRequest$Outbound` instead. */
  export type Outbound = PredictDurationRequest$Outbound;
}

export function predictDurationRequestToJSON(
  predictDurationRequest: PredictDurationRequest,
): string {
  return JSON.stringify(
    PredictDurationRequest$outboundSchema.parse(predictDurationRequest),
  );
}

export function predictDurationRequestFromJSON(
  jsonString: string,
): SafeParseResult<PredictDurationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PredictDurationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PredictDurationRequest' from JSON`,
  );
}

/** @internal */
export const PredictDurationResponse$inboundSchema: z.ZodType<
  PredictDurationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  duration: z.number().optional(),
});

/** @internal */
export type PredictDurationResponse$Outbound = {
  duration?: number | undefined;
};

/** @internal */
export const PredictDurationResponse$outboundSchema: z.ZodType<
  PredictDurationResponse$Outbound,
  z.ZodTypeDef,
  PredictDurationResponse
> = z.object({
  duration: z.number().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PredictDurationResponse$ {
  /** @deprecated use `PredictDurationResponse$inboundSchema` instead. */
  export const inboundSchema = PredictDurationResponse$inboundSchema;
  /** @deprecated use `PredictDurationResponse$outboundSchema` instead. */
  export const outboundSchema = PredictDurationResponse$outboundSchema;
  /** @deprecated use `PredictDurationResponse$Outbound` instead. */
  export type Outbound = PredictDurationResponse$Outbound;
}

export function predictDurationResponseToJSON(
  predictDurationResponse: PredictDurationResponse,
): string {
  return JSON.stringify(
    PredictDurationResponse$outboundSchema.parse(predictDurationResponse),
  );
}

export function predictDurationResponseFromJSON(
  jsonString: string,
): SafeParseResult<PredictDurationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PredictDurationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PredictDurationResponse' from JSON`,
  );
}
