/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ConvertTextToSpeechParameters,
  ConvertTextToSpeechParameters$inboundSchema,
  ConvertTextToSpeechParameters$Outbound,
  ConvertTextToSpeechParameters$outboundSchema,
} from "./converttexttospeechparameters.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The language code of the text
 */
export const APIConvertTextToSpeechUsingCharacterRequestLanguage = {
  En: "en",
  Ko: "ko",
  Ja: "ja",
  Es: "es",
  Pt: "pt",
} as const;
/**
 * The language code of the text
 */
export type APIConvertTextToSpeechUsingCharacterRequestLanguage = ClosedEnum<
  typeof APIConvertTextToSpeechUsingCharacterRequestLanguage
>;

/**
 * The desired output format of the audio file (wav, mp3). Default is wav.
 */
export const APIConvertTextToSpeechUsingCharacterRequestOutputFormat = {
  Wav: "wav",
  Mp3: "mp3",
} as const;
/**
 * The desired output format of the audio file (wav, mp3). Default is wav.
 */
export type APIConvertTextToSpeechUsingCharacterRequestOutputFormat =
  ClosedEnum<typeof APIConvertTextToSpeechUsingCharacterRequestOutputFormat>;

export type APIConvertTextToSpeechUsingCharacterRequest = {
  /**
   * The text to convert to speech
   */
  text: string;
  /**
   * The language code of the text
   */
  language: APIConvertTextToSpeechUsingCharacterRequestLanguage;
  /**
   * The style of character to use for the text-to-speech conversion
   */
  style?: string | undefined;
  /**
   * The model type to use for the text-to-speech conversion
   */
  model?: string | undefined;
  /**
   * The desired output format of the audio file (wav, mp3). Default is wav.
   */
  outputFormat?:
    | APIConvertTextToSpeechUsingCharacterRequestOutputFormat
    | undefined;
  voiceSettings?: ConvertTextToSpeechParameters | undefined;
  /**
   * Return phoneme timing data with the audio
   */
  includePhonemes?: boolean | undefined;
};

/** @internal */
export const APIConvertTextToSpeechUsingCharacterRequestLanguage$inboundSchema:
  z.ZodNativeEnum<typeof APIConvertTextToSpeechUsingCharacterRequestLanguage> =
    z.nativeEnum(APIConvertTextToSpeechUsingCharacterRequestLanguage);

/** @internal */
export const APIConvertTextToSpeechUsingCharacterRequestLanguage$outboundSchema:
  z.ZodNativeEnum<typeof APIConvertTextToSpeechUsingCharacterRequestLanguage> =
    APIConvertTextToSpeechUsingCharacterRequestLanguage$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APIConvertTextToSpeechUsingCharacterRequestLanguage$ {
  /** @deprecated use `APIConvertTextToSpeechUsingCharacterRequestLanguage$inboundSchema` instead. */
  export const inboundSchema =
    APIConvertTextToSpeechUsingCharacterRequestLanguage$inboundSchema;
  /** @deprecated use `APIConvertTextToSpeechUsingCharacterRequestLanguage$outboundSchema` instead. */
  export const outboundSchema =
    APIConvertTextToSpeechUsingCharacterRequestLanguage$outboundSchema;
}

/** @internal */
export const APIConvertTextToSpeechUsingCharacterRequestOutputFormat$inboundSchema:
  z.ZodNativeEnum<
    typeof APIConvertTextToSpeechUsingCharacterRequestOutputFormat
  > = z.nativeEnum(APIConvertTextToSpeechUsingCharacterRequestOutputFormat);

/** @internal */
export const APIConvertTextToSpeechUsingCharacterRequestOutputFormat$outboundSchema:
  z.ZodNativeEnum<
    typeof APIConvertTextToSpeechUsingCharacterRequestOutputFormat
  > = APIConvertTextToSpeechUsingCharacterRequestOutputFormat$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APIConvertTextToSpeechUsingCharacterRequestOutputFormat$ {
  /** @deprecated use `APIConvertTextToSpeechUsingCharacterRequestOutputFormat$inboundSchema` instead. */
  export const inboundSchema =
    APIConvertTextToSpeechUsingCharacterRequestOutputFormat$inboundSchema;
  /** @deprecated use `APIConvertTextToSpeechUsingCharacterRequestOutputFormat$outboundSchema` instead. */
  export const outboundSchema =
    APIConvertTextToSpeechUsingCharacterRequestOutputFormat$outboundSchema;
}

/** @internal */
export const APIConvertTextToSpeechUsingCharacterRequest$inboundSchema:
  z.ZodType<
    APIConvertTextToSpeechUsingCharacterRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    text: z.string(),
    language: APIConvertTextToSpeechUsingCharacterRequestLanguage$inboundSchema,
    style: z.string().optional(),
    model: z.string().default("sona_speech_1"),
    output_format:
      APIConvertTextToSpeechUsingCharacterRequestOutputFormat$inboundSchema
        .default("wav"),
    voice_settings: ConvertTextToSpeechParameters$inboundSchema.optional(),
    include_phonemes: z.boolean().default(false),
  }).transform((v) => {
    return remap$(v, {
      "output_format": "outputFormat",
      "voice_settings": "voiceSettings",
      "include_phonemes": "includePhonemes",
    });
  });

/** @internal */
export type APIConvertTextToSpeechUsingCharacterRequest$Outbound = {
  text: string;
  language: string;
  style?: string | undefined;
  model: string;
  output_format: string;
  voice_settings?: ConvertTextToSpeechParameters$Outbound | undefined;
  include_phonemes: boolean;
};

/** @internal */
export const APIConvertTextToSpeechUsingCharacterRequest$outboundSchema:
  z.ZodType<
    APIConvertTextToSpeechUsingCharacterRequest$Outbound,
    z.ZodTypeDef,
    APIConvertTextToSpeechUsingCharacterRequest
  > = z.object({
    text: z.string(),
    language:
      APIConvertTextToSpeechUsingCharacterRequestLanguage$outboundSchema,
    style: z.string().optional(),
    model: z.string().default("sona_speech_1"),
    outputFormat:
      APIConvertTextToSpeechUsingCharacterRequestOutputFormat$outboundSchema
        .default("wav"),
    voiceSettings: ConvertTextToSpeechParameters$outboundSchema.optional(),
    includePhonemes: z.boolean().default(false),
  }).transform((v) => {
    return remap$(v, {
      outputFormat: "output_format",
      voiceSettings: "voice_settings",
      includePhonemes: "include_phonemes",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace APIConvertTextToSpeechUsingCharacterRequest$ {
  /** @deprecated use `APIConvertTextToSpeechUsingCharacterRequest$inboundSchema` instead. */
  export const inboundSchema =
    APIConvertTextToSpeechUsingCharacterRequest$inboundSchema;
  /** @deprecated use `APIConvertTextToSpeechUsingCharacterRequest$outboundSchema` instead. */
  export const outboundSchema =
    APIConvertTextToSpeechUsingCharacterRequest$outboundSchema;
  /** @deprecated use `APIConvertTextToSpeechUsingCharacterRequest$Outbound` instead. */
  export type Outbound = APIConvertTextToSpeechUsingCharacterRequest$Outbound;
}

export function apiConvertTextToSpeechUsingCharacterRequestToJSON(
  apiConvertTextToSpeechUsingCharacterRequest:
    APIConvertTextToSpeechUsingCharacterRequest,
): string {
  return JSON.stringify(
    APIConvertTextToSpeechUsingCharacterRequest$outboundSchema.parse(
      apiConvertTextToSpeechUsingCharacterRequest,
    ),
  );
}

export function apiConvertTextToSpeechUsingCharacterRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  APIConvertTextToSpeechUsingCharacterRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      APIConvertTextToSpeechUsingCharacterRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'APIConvertTextToSpeechUsingCharacterRequest' from JSON`,
  );
}
