/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Bad request error details
 */
export type BadRequestErrorResponseMessage = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  error: string;
  /**
   * HTTP status code
   */
  statusCode: number;
};

/** @internal */
export const BadRequestErrorResponseMessage$inboundSchema: z.ZodType<
  BadRequestErrorResponseMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
  status_code: z.number(),
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
  });
});

/** @internal */
export type BadRequestErrorResponseMessage$Outbound = {
  message: string;
  error: string;
  status_code: number;
};

/** @internal */
export const BadRequestErrorResponseMessage$outboundSchema: z.ZodType<
  BadRequestErrorResponseMessage$Outbound,
  z.ZodTypeDef,
  BadRequestErrorResponseMessage
> = z.object({
  message: z.string(),
  error: z.string(),
  statusCode: z.number(),
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BadRequestErrorResponseMessage$ {
  /** @deprecated use `BadRequestErrorResponseMessage$inboundSchema` instead. */
  export const inboundSchema = BadRequestErrorResponseMessage$inboundSchema;
  /** @deprecated use `BadRequestErrorResponseMessage$outboundSchema` instead. */
  export const outboundSchema = BadRequestErrorResponseMessage$outboundSchema;
  /** @deprecated use `BadRequestErrorResponseMessage$Outbound` instead. */
  export type Outbound = BadRequestErrorResponseMessage$Outbound;
}

export function badRequestErrorResponseMessageToJSON(
  badRequestErrorResponseMessage: BadRequestErrorResponseMessage,
): string {
  return JSON.stringify(
    BadRequestErrorResponseMessage$outboundSchema.parse(
      badRequestErrorResponseMessage,
    ),
  );
}

export function badRequestErrorResponseMessageFromJSON(
  jsonString: string,
): SafeParseResult<BadRequestErrorResponseMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BadRequestErrorResponseMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadRequestErrorResponseMessage' from JSON`,
  );
}
