/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ConvertTextToSpeechParameters = {
  pitchShift?: number | undefined;
  pitchVariance?: number | undefined;
  speed?: number | undefined;
  /**
   * Duration parameter for TTS generation
   */
  duration?: number | undefined;
  /**
   * Similarity parameter for voice matching
   */
  similarity?: number | undefined;
  /**
   * Text guidance parameter for generation control
   */
  textGuidance?: number | undefined;
  /**
   * Subharmonic amplitude control parameter
   */
  subharmonicAmplitudeControl?: number | undefined;
};

/** @internal */
export const ConvertTextToSpeechParameters$inboundSchema: z.ZodType<
  ConvertTextToSpeechParameters,
  z.ZodTypeDef,
  unknown
> = z.object({
  pitch_shift: z.number().default(0),
  pitch_variance: z.number().default(1),
  speed: z.number().default(1),
  duration: z.number().default(0),
  similarity: z.number().default(3),
  text_guidance: z.number().default(1),
  subharmonic_amplitude_control: z.number().default(1),
}).transform((v) => {
  return remap$(v, {
    "pitch_shift": "pitchShift",
    "pitch_variance": "pitchVariance",
    "text_guidance": "textGuidance",
    "subharmonic_amplitude_control": "subharmonicAmplitudeControl",
  });
});

/** @internal */
export type ConvertTextToSpeechParameters$Outbound = {
  pitch_shift: number;
  pitch_variance: number;
  speed: number;
  duration: number;
  similarity: number;
  text_guidance: number;
  subharmonic_amplitude_control: number;
};

/** @internal */
export const ConvertTextToSpeechParameters$outboundSchema: z.ZodType<
  ConvertTextToSpeechParameters$Outbound,
  z.ZodTypeDef,
  ConvertTextToSpeechParameters
> = z.object({
  pitchShift: z.number().default(0),
  pitchVariance: z.number().default(1),
  speed: z.number().default(1),
  duration: z.number().default(0),
  similarity: z.number().default(3),
  textGuidance: z.number().default(1),
  subharmonicAmplitudeControl: z.number().default(1),
}).transform((v) => {
  return remap$(v, {
    pitchShift: "pitch_shift",
    pitchVariance: "pitch_variance",
    textGuidance: "text_guidance",
    subharmonicAmplitudeControl: "subharmonic_amplitude_control",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConvertTextToSpeechParameters$ {
  /** @deprecated use `ConvertTextToSpeechParameters$inboundSchema` instead. */
  export const inboundSchema = ConvertTextToSpeechParameters$inboundSchema;
  /** @deprecated use `ConvertTextToSpeechParameters$outboundSchema` instead. */
  export const outboundSchema = ConvertTextToSpeechParameters$outboundSchema;
  /** @deprecated use `ConvertTextToSpeechParameters$Outbound` instead. */
  export type Outbound = ConvertTextToSpeechParameters$Outbound;
}

export function convertTextToSpeechParametersToJSON(
  convertTextToSpeechParameters: ConvertTextToSpeechParameters,
): string {
  return JSON.stringify(
    ConvertTextToSpeechParameters$outboundSchema.parse(
      convertTextToSpeechParameters,
    ),
  );
}

export function convertTextToSpeechParametersFromJSON(
  jsonString: string,
): SafeParseResult<ConvertTextToSpeechParameters, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConvertTextToSpeechParameters$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConvertTextToSpeechParameters' from JSON`,
  );
}
