/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreateClonedVoiceUploadResponse = {
  /**
   * Unique identifier for the created voice
   */
  voiceId: string;
};

/** @internal */
export const CreateClonedVoiceUploadResponse$inboundSchema: z.ZodType<
  CreateClonedVoiceUploadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  voice_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "voice_id": "voiceId",
  });
});

/** @internal */
export type CreateClonedVoiceUploadResponse$Outbound = {
  voice_id: string;
};

/** @internal */
export const CreateClonedVoiceUploadResponse$outboundSchema: z.ZodType<
  CreateClonedVoiceUploadResponse$Outbound,
  z.ZodTypeDef,
  CreateClonedVoiceUploadResponse
> = z.object({
  voiceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    voiceId: "voice_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateClonedVoiceUploadResponse$ {
  /** @deprecated use `CreateClonedVoiceUploadResponse$inboundSchema` instead. */
  export const inboundSchema = CreateClonedVoiceUploadResponse$inboundSchema;
  /** @deprecated use `CreateClonedVoiceUploadResponse$outboundSchema` instead. */
  export const outboundSchema = CreateClonedVoiceUploadResponse$outboundSchema;
  /** @deprecated use `CreateClonedVoiceUploadResponse$Outbound` instead. */
  export type Outbound = CreateClonedVoiceUploadResponse$Outbound;
}

export function createClonedVoiceUploadResponseToJSON(
  createClonedVoiceUploadResponse: CreateClonedVoiceUploadResponse,
): string {
  return JSON.stringify(
    CreateClonedVoiceUploadResponse$outboundSchema.parse(
      createClonedVoiceUploadResponse,
    ),
  );
}

export function createClonedVoiceUploadResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateClonedVoiceUploadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateClonedVoiceUploadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateClonedVoiceUploadResponse' from JSON`,
  );
}
