/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Forbidden error details
 */
export type ForbiddenErrorResponseMessage = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  error: string;
  /**
   * HTTP status code
   */
  statusCode: number;
};

/** @internal */
export const ForbiddenErrorResponseMessage$inboundSchema: z.ZodType<
  ForbiddenErrorResponseMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
  status_code: z.number(),
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
  });
});

/** @internal */
export type ForbiddenErrorResponseMessage$Outbound = {
  message: string;
  error: string;
  status_code: number;
};

/** @internal */
export const ForbiddenErrorResponseMessage$outboundSchema: z.ZodType<
  ForbiddenErrorResponseMessage$Outbound,
  z.ZodTypeDef,
  ForbiddenErrorResponseMessage
> = z.object({
  message: z.string(),
  error: z.string(),
  statusCode: z.number(),
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ForbiddenErrorResponseMessage$ {
  /** @deprecated use `ForbiddenErrorResponseMessage$inboundSchema` instead. */
  export const inboundSchema = ForbiddenErrorResponseMessage$inboundSchema;
  /** @deprecated use `ForbiddenErrorResponseMessage$outboundSchema` instead. */
  export const outboundSchema = ForbiddenErrorResponseMessage$outboundSchema;
  /** @deprecated use `ForbiddenErrorResponseMessage$Outbound` instead. */
  export type Outbound = ForbiddenErrorResponseMessage$Outbound;
}

export function forbiddenErrorResponseMessageToJSON(
  forbiddenErrorResponseMessage: ForbiddenErrorResponseMessage,
): string {
  return JSON.stringify(
    ForbiddenErrorResponseMessage$outboundSchema.parse(
      forbiddenErrorResponseMessage,
    ),
  );
}

export function forbiddenErrorResponseMessageFromJSON(
  jsonString: string,
): SafeParseResult<ForbiddenErrorResponseMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ForbiddenErrorResponseMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ForbiddenErrorResponseMessage' from JSON`,
  );
}
