/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  GetAPICharacterResponseData,
  GetAPICharacterResponseData$inboundSchema,
  GetAPICharacterResponseData$Outbound,
  GetAPICharacterResponseData$outboundSchema,
} from "./getapicharacterresponsedata.js";

export type GetAPICharacterListResponse = {
  /**
   * List of character items
   */
  items: Array<GetAPICharacterResponseData>;
  /**
   * Total number of available characters (might be approximate or removed in future)
   */
  total: number;
  /**
   * Token for fetching the next page of results. Undefined if no more pages.
   */
  nextPageToken?: string | undefined;
};

/** @internal */
export const GetAPICharacterListResponse$inboundSchema: z.ZodType<
  GetAPICharacterListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(GetAPICharacterResponseData$inboundSchema),
  total: z.number(),
  next_page_token: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "next_page_token": "nextPageToken",
  });
});

/** @internal */
export type GetAPICharacterListResponse$Outbound = {
  items: Array<GetAPICharacterResponseData$Outbound>;
  total: number;
  next_page_token?: string | undefined;
};

/** @internal */
export const GetAPICharacterListResponse$outboundSchema: z.ZodType<
  GetAPICharacterListResponse$Outbound,
  z.ZodTypeDef,
  GetAPICharacterListResponse
> = z.object({
  items: z.array(GetAPICharacterResponseData$outboundSchema),
  total: z.number(),
  nextPageToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    nextPageToken: "next_page_token",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAPICharacterListResponse$ {
  /** @deprecated use `GetAPICharacterListResponse$inboundSchema` instead. */
  export const inboundSchema = GetAPICharacterListResponse$inboundSchema;
  /** @deprecated use `GetAPICharacterListResponse$outboundSchema` instead. */
  export const outboundSchema = GetAPICharacterListResponse$outboundSchema;
  /** @deprecated use `GetAPICharacterListResponse$Outbound` instead. */
  export type Outbound = GetAPICharacterListResponse$Outbound;
}

export function getAPICharacterListResponseToJSON(
  getAPICharacterListResponse: GetAPICharacterListResponse,
): string {
  return JSON.stringify(
    GetAPICharacterListResponse$outboundSchema.parse(
      getAPICharacterListResponse,
    ),
  );
}

export function getAPICharacterListResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAPICharacterListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAPICharacterListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAPICharacterListResponse' from JSON`,
  );
}
