/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type GetCreditBalanceResponse = {
  /**
   * Credit balance of the user
   */
  balance: number | null;
};

/** @internal */
export const GetCreditBalanceResponse$inboundSchema: z.ZodType<
  GetCreditBalanceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  balance: z.nullable(z.number()),
});

/** @internal */
export type GetCreditBalanceResponse$Outbound = {
  balance: number | null;
};

/** @internal */
export const GetCreditBalanceResponse$outboundSchema: z.ZodType<
  GetCreditBalanceResponse$Outbound,
  z.ZodTypeDef,
  GetCreditBalanceResponse
> = z.object({
  balance: z.nullable(z.number()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCreditBalanceResponse$ {
  /** @deprecated use `GetCreditBalanceResponse$inboundSchema` instead. */
  export const inboundSchema = GetCreditBalanceResponse$inboundSchema;
  /** @deprecated use `GetCreditBalanceResponse$outboundSchema` instead. */
  export const outboundSchema = GetCreditBalanceResponse$outboundSchema;
  /** @deprecated use `GetCreditBalanceResponse$Outbound` instead. */
  export type Outbound = GetCreditBalanceResponse$Outbound;
}

export function getCreditBalanceResponseToJSON(
  getCreditBalanceResponse: GetCreditBalanceResponse,
): string {
  return JSON.stringify(
    GetCreditBalanceResponse$outboundSchema.parse(getCreditBalanceResponse),
  );
}

export function getCreditBalanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCreditBalanceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreditBalanceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreditBalanceResponse' from JSON`,
  );
}
