/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type GetCustomVoiceResponseData = {
  /**
   * Unique identifier for the custom voice
   */
  voiceId: string;
  /**
   * Name of the custom voice
   */
  name: string;
  /**
   * Description of the custom voice
   */
  description: string;
};

/** @internal */
export const GetCustomVoiceResponseData$inboundSchema: z.ZodType<
  GetCustomVoiceResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  voice_id: z.string(),
  name: z.string(),
  description: z.string(),
}).transform((v) => {
  return remap$(v, {
    "voice_id": "voiceId",
  });
});

/** @internal */
export type GetCustomVoiceResponseData$Outbound = {
  voice_id: string;
  name: string;
  description: string;
};

/** @internal */
export const GetCustomVoiceResponseData$outboundSchema: z.ZodType<
  GetCustomVoiceResponseData$Outbound,
  z.ZodTypeDef,
  GetCustomVoiceResponseData
> = z.object({
  voiceId: z.string(),
  name: z.string(),
  description: z.string(),
}).transform((v) => {
  return remap$(v, {
    voiceId: "voice_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomVoiceResponseData$ {
  /** @deprecated use `GetCustomVoiceResponseData$inboundSchema` instead. */
  export const inboundSchema = GetCustomVoiceResponseData$inboundSchema;
  /** @deprecated use `GetCustomVoiceResponseData$outboundSchema` instead. */
  export const outboundSchema = GetCustomVoiceResponseData$outboundSchema;
  /** @deprecated use `GetCustomVoiceResponseData$Outbound` instead. */
  export type Outbound = GetCustomVoiceResponseData$Outbound;
}

export function getCustomVoiceResponseDataToJSON(
  getCustomVoiceResponseData: GetCustomVoiceResponseData,
): string {
  return JSON.stringify(
    GetCustomVoiceResponseData$outboundSchema.parse(getCustomVoiceResponseData),
  );
}

export function getCustomVoiceResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomVoiceResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomVoiceResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomVoiceResponseData' from JSON`,
  );
}
