/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type GetSingleClonedVoiceResponse = {
  /**
   * Unique identifier for the voice
   */
  voiceId: string;
  /**
   * Name of the voice
   */
  name: string;
  /**
   * Description of the voice
   */
  description: string;
};

/** @internal */
export const GetSingleClonedVoiceResponse$inboundSchema: z.ZodType<
  GetSingleClonedVoiceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  voice_id: z.string(),
  name: z.string(),
  description: z.string(),
}).transform((v) => {
  return remap$(v, {
    "voice_id": "voiceId",
  });
});

/** @internal */
export type GetSingleClonedVoiceResponse$Outbound = {
  voice_id: string;
  name: string;
  description: string;
};

/** @internal */
export const GetSingleClonedVoiceResponse$outboundSchema: z.ZodType<
  GetSingleClonedVoiceResponse$Outbound,
  z.ZodTypeDef,
  GetSingleClonedVoiceResponse
> = z.object({
  voiceId: z.string(),
  name: z.string(),
  description: z.string(),
}).transform((v) => {
  return remap$(v, {
    voiceId: "voice_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSingleClonedVoiceResponse$ {
  /** @deprecated use `GetSingleClonedVoiceResponse$inboundSchema` instead. */
  export const inboundSchema = GetSingleClonedVoiceResponse$inboundSchema;
  /** @deprecated use `GetSingleClonedVoiceResponse$outboundSchema` instead. */
  export const outboundSchema = GetSingleClonedVoiceResponse$outboundSchema;
  /** @deprecated use `GetSingleClonedVoiceResponse$Outbound` instead. */
  export type Outbound = GetSingleClonedVoiceResponse$Outbound;
}

export function getSingleClonedVoiceResponseToJSON(
  getSingleClonedVoiceResponse: GetSingleClonedVoiceResponse,
): string {
  return JSON.stringify(
    GetSingleClonedVoiceResponse$outboundSchema.parse(
      getSingleClonedVoiceResponse,
    ),
  );
}

export function getSingleClonedVoiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSingleClonedVoiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSingleClonedVoiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSingleClonedVoiceResponse' from JSON`,
  );
}
