/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  GetUsageResponseV1Data,
  GetUsageResponseV1Data$inboundSchema,
  GetUsageResponseV1Data$Outbound,
  GetUsageResponseV1Data$outboundSchema,
} from "./getusageresponsev1data.js";

export type GetUsageListV1Response = {
  usages: Array<GetUsageResponseV1Data>;
};

/** @internal */
export const GetUsageListV1Response$inboundSchema: z.ZodType<
  GetUsageListV1Response,
  z.ZodTypeDef,
  unknown
> = z.object({
  usages: z.array(GetUsageResponseV1Data$inboundSchema),
});

/** @internal */
export type GetUsageListV1Response$Outbound = {
  usages: Array<GetUsageResponseV1Data$Outbound>;
};

/** @internal */
export const GetUsageListV1Response$outboundSchema: z.ZodType<
  GetUsageListV1Response$Outbound,
  z.ZodTypeDef,
  GetUsageListV1Response
> = z.object({
  usages: z.array(GetUsageResponseV1Data$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUsageListV1Response$ {
  /** @deprecated use `GetUsageListV1Response$inboundSchema` instead. */
  export const inboundSchema = GetUsageListV1Response$inboundSchema;
  /** @deprecated use `GetUsageListV1Response$outboundSchema` instead. */
  export const outboundSchema = GetUsageListV1Response$outboundSchema;
  /** @deprecated use `GetUsageListV1Response$Outbound` instead. */
  export type Outbound = GetUsageListV1Response$Outbound;
}

export function getUsageListV1ResponseToJSON(
  getUsageListV1Response: GetUsageListV1Response,
): string {
  return JSON.stringify(
    GetUsageListV1Response$outboundSchema.parse(getUsageListV1Response),
  );
}

export function getUsageListV1ResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUsageListV1Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUsageListV1Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUsageListV1Response' from JSON`,
  );
}
