/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Internal server error details
 */
export type InternalServerErrorResponseMessage = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  error: string;
  /**
   * HTTP status code
   */
  statusCode: number;
};

/** @internal */
export const InternalServerErrorResponseMessage$inboundSchema: z.ZodType<
  InternalServerErrorResponseMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
  status_code: z.number(),
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
  });
});

/** @internal */
export type InternalServerErrorResponseMessage$Outbound = {
  message: string;
  error: string;
  status_code: number;
};

/** @internal */
export const InternalServerErrorResponseMessage$outboundSchema: z.ZodType<
  InternalServerErrorResponseMessage$Outbound,
  z.ZodTypeDef,
  InternalServerErrorResponseMessage
> = z.object({
  message: z.string(),
  error: z.string(),
  statusCode: z.number(),
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InternalServerErrorResponseMessage$ {
  /** @deprecated use `InternalServerErrorResponseMessage$inboundSchema` instead. */
  export const inboundSchema = InternalServerErrorResponseMessage$inboundSchema;
  /** @deprecated use `InternalServerErrorResponseMessage$outboundSchema` instead. */
  export const outboundSchema =
    InternalServerErrorResponseMessage$outboundSchema;
  /** @deprecated use `InternalServerErrorResponseMessage$Outbound` instead. */
  export type Outbound = InternalServerErrorResponseMessage$Outbound;
}

export function internalServerErrorResponseMessageToJSON(
  internalServerErrorResponseMessage: InternalServerErrorResponseMessage,
): string {
  return JSON.stringify(
    InternalServerErrorResponseMessage$outboundSchema.parse(
      internalServerErrorResponseMessage,
    ),
  );
}

export function internalServerErrorResponseMessageFromJSON(
  jsonString: string,
): SafeParseResult<InternalServerErrorResponseMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      InternalServerErrorResponseMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InternalServerErrorResponseMessage' from JSON`,
  );
}
