/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Payload too large error details
 */
export type PayloadTooLargeErrorResponseMessage = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  error: string;
  /**
   * HTTP status code
   */
  statusCode: number;
};

/** @internal */
export const PayloadTooLargeErrorResponseMessage$inboundSchema: z.ZodType<
  PayloadTooLargeErrorResponseMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
  status_code: z.number(),
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
  });
});

/** @internal */
export type PayloadTooLargeErrorResponseMessage$Outbound = {
  message: string;
  error: string;
  status_code: number;
};

/** @internal */
export const PayloadTooLargeErrorResponseMessage$outboundSchema: z.ZodType<
  PayloadTooLargeErrorResponseMessage$Outbound,
  z.ZodTypeDef,
  PayloadTooLargeErrorResponseMessage
> = z.object({
  message: z.string(),
  error: z.string(),
  statusCode: z.number(),
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayloadTooLargeErrorResponseMessage$ {
  /** @deprecated use `PayloadTooLargeErrorResponseMessage$inboundSchema` instead. */
  export const inboundSchema =
    PayloadTooLargeErrorResponseMessage$inboundSchema;
  /** @deprecated use `PayloadTooLargeErrorResponseMessage$outboundSchema` instead. */
  export const outboundSchema =
    PayloadTooLargeErrorResponseMessage$outboundSchema;
  /** @deprecated use `PayloadTooLargeErrorResponseMessage$Outbound` instead. */
  export type Outbound = PayloadTooLargeErrorResponseMessage$Outbound;
}

export function payloadTooLargeErrorResponseMessageToJSON(
  payloadTooLargeErrorResponseMessage: PayloadTooLargeErrorResponseMessage,
): string {
  return JSON.stringify(
    PayloadTooLargeErrorResponseMessage$outboundSchema.parse(
      payloadTooLargeErrorResponseMessage,
    ),
  );
}

export function payloadTooLargeErrorResponseMessageFromJSON(
  jsonString: string,
): SafeParseResult<PayloadTooLargeErrorResponseMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PayloadTooLargeErrorResponseMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayloadTooLargeErrorResponseMessage' from JSON`,
  );
}
