/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Payment required error details
 */
export type PaymentRequiredErrorResponseMessage = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  error: string;
  /**
   * HTTP status code
   */
  statusCode: number;
};

/** @internal */
export const PaymentRequiredErrorResponseMessage$inboundSchema: z.ZodType<
  PaymentRequiredErrorResponseMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
  status_code: z.number(),
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
  });
});

/** @internal */
export type PaymentRequiredErrorResponseMessage$Outbound = {
  message: string;
  error: string;
  status_code: number;
};

/** @internal */
export const PaymentRequiredErrorResponseMessage$outboundSchema: z.ZodType<
  PaymentRequiredErrorResponseMessage$Outbound,
  z.ZodTypeDef,
  PaymentRequiredErrorResponseMessage
> = z.object({
  message: z.string(),
  error: z.string(),
  statusCode: z.number(),
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentRequiredErrorResponseMessage$ {
  /** @deprecated use `PaymentRequiredErrorResponseMessage$inboundSchema` instead. */
  export const inboundSchema =
    PaymentRequiredErrorResponseMessage$inboundSchema;
  /** @deprecated use `PaymentRequiredErrorResponseMessage$outboundSchema` instead. */
  export const outboundSchema =
    PaymentRequiredErrorResponseMessage$outboundSchema;
  /** @deprecated use `PaymentRequiredErrorResponseMessage$Outbound` instead. */
  export type Outbound = PaymentRequiredErrorResponseMessage$Outbound;
}

export function paymentRequiredErrorResponseMessageToJSON(
  paymentRequiredErrorResponseMessage: PaymentRequiredErrorResponseMessage,
): string {
  return JSON.stringify(
    PaymentRequiredErrorResponseMessage$outboundSchema.parse(
      paymentRequiredErrorResponseMessage,
    ),
  );
}

export function paymentRequiredErrorResponseMessageFromJSON(
  jsonString: string,
): SafeParseResult<PaymentRequiredErrorResponseMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaymentRequiredErrorResponseMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentRequiredErrorResponseMessage' from JSON`,
  );
}
