/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ConvertTextToSpeechParameters,
  ConvertTextToSpeechParameters$inboundSchema,
  ConvertTextToSpeechParameters$Outbound,
  ConvertTextToSpeechParameters$outboundSchema,
} from "./converttexttospeechparameters.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Language code of the voice
 */
export const PredictTTSDurationUsingCharacterRequestLanguage = {
  En: "en",
  Ko: "ko",
  Ja: "ja",
  Es: "es",
  Pt: "pt",
} as const;
/**
 * Language code of the voice
 */
export type PredictTTSDurationUsingCharacterRequestLanguage = ClosedEnum<
  typeof PredictTTSDurationUsingCharacterRequestLanguage
>;

/**
 * The desired output format of the audio file (wav, mp3). Default is wav.
 */
export const PredictTTSDurationUsingCharacterRequestOutputFormat = {
  Wav: "wav",
  Mp3: "mp3",
} as const;
/**
 * The desired output format of the audio file (wav, mp3). Default is wav.
 */
export type PredictTTSDurationUsingCharacterRequestOutputFormat = ClosedEnum<
  typeof PredictTTSDurationUsingCharacterRequestOutputFormat
>;

export type PredictTTSDurationUsingCharacterRequest = {
  /**
   * The text to convert to speech. Max length is 300 characters.
   */
  text: string;
  /**
   * Language code of the voice
   */
  language: PredictTTSDurationUsingCharacterRequestLanguage;
  /**
   * The style of character to use for the text-to-speech conversion
   */
  style?: string | undefined;
  /**
   * The model type to use for the text-to-speech conversion
   */
  model?: string | undefined;
  /**
   * The desired output format of the audio file (wav, mp3). Default is wav.
   */
  outputFormat?:
    | PredictTTSDurationUsingCharacterRequestOutputFormat
    | undefined;
  voiceSettings?: ConvertTextToSpeechParameters | undefined;
};

/** @internal */
export const PredictTTSDurationUsingCharacterRequestLanguage$inboundSchema:
  z.ZodNativeEnum<typeof PredictTTSDurationUsingCharacterRequestLanguage> = z
    .nativeEnum(PredictTTSDurationUsingCharacterRequestLanguage);

/** @internal */
export const PredictTTSDurationUsingCharacterRequestLanguage$outboundSchema:
  z.ZodNativeEnum<typeof PredictTTSDurationUsingCharacterRequestLanguage> =
    PredictTTSDurationUsingCharacterRequestLanguage$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PredictTTSDurationUsingCharacterRequestLanguage$ {
  /** @deprecated use `PredictTTSDurationUsingCharacterRequestLanguage$inboundSchema` instead. */
  export const inboundSchema =
    PredictTTSDurationUsingCharacterRequestLanguage$inboundSchema;
  /** @deprecated use `PredictTTSDurationUsingCharacterRequestLanguage$outboundSchema` instead. */
  export const outboundSchema =
    PredictTTSDurationUsingCharacterRequestLanguage$outboundSchema;
}

/** @internal */
export const PredictTTSDurationUsingCharacterRequestOutputFormat$inboundSchema:
  z.ZodNativeEnum<typeof PredictTTSDurationUsingCharacterRequestOutputFormat> =
    z.nativeEnum(PredictTTSDurationUsingCharacterRequestOutputFormat);

/** @internal */
export const PredictTTSDurationUsingCharacterRequestOutputFormat$outboundSchema:
  z.ZodNativeEnum<typeof PredictTTSDurationUsingCharacterRequestOutputFormat> =
    PredictTTSDurationUsingCharacterRequestOutputFormat$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PredictTTSDurationUsingCharacterRequestOutputFormat$ {
  /** @deprecated use `PredictTTSDurationUsingCharacterRequestOutputFormat$inboundSchema` instead. */
  export const inboundSchema =
    PredictTTSDurationUsingCharacterRequestOutputFormat$inboundSchema;
  /** @deprecated use `PredictTTSDurationUsingCharacterRequestOutputFormat$outboundSchema` instead. */
  export const outboundSchema =
    PredictTTSDurationUsingCharacterRequestOutputFormat$outboundSchema;
}

/** @internal */
export const PredictTTSDurationUsingCharacterRequest$inboundSchema: z.ZodType<
  PredictTTSDurationUsingCharacterRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.string(),
  language: PredictTTSDurationUsingCharacterRequestLanguage$inboundSchema,
  style: z.string().optional(),
  model: z.string().default("sona_speech_1"),
  output_format:
    PredictTTSDurationUsingCharacterRequestOutputFormat$inboundSchema.default(
      "wav",
    ),
  voice_settings: ConvertTextToSpeechParameters$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "output_format": "outputFormat",
    "voice_settings": "voiceSettings",
  });
});

/** @internal */
export type PredictTTSDurationUsingCharacterRequest$Outbound = {
  text: string;
  language: string;
  style?: string | undefined;
  model: string;
  output_format: string;
  voice_settings?: ConvertTextToSpeechParameters$Outbound | undefined;
};

/** @internal */
export const PredictTTSDurationUsingCharacterRequest$outboundSchema: z.ZodType<
  PredictTTSDurationUsingCharacterRequest$Outbound,
  z.ZodTypeDef,
  PredictTTSDurationUsingCharacterRequest
> = z.object({
  text: z.string(),
  language: PredictTTSDurationUsingCharacterRequestLanguage$outboundSchema,
  style: z.string().optional(),
  model: z.string().default("sona_speech_1"),
  outputFormat:
    PredictTTSDurationUsingCharacterRequestOutputFormat$outboundSchema.default(
      "wav",
    ),
  voiceSettings: ConvertTextToSpeechParameters$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    outputFormat: "output_format",
    voiceSettings: "voice_settings",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PredictTTSDurationUsingCharacterRequest$ {
  /** @deprecated use `PredictTTSDurationUsingCharacterRequest$inboundSchema` instead. */
  export const inboundSchema =
    PredictTTSDurationUsingCharacterRequest$inboundSchema;
  /** @deprecated use `PredictTTSDurationUsingCharacterRequest$outboundSchema` instead. */
  export const outboundSchema =
    PredictTTSDurationUsingCharacterRequest$outboundSchema;
  /** @deprecated use `PredictTTSDurationUsingCharacterRequest$Outbound` instead. */
  export type Outbound = PredictTTSDurationUsingCharacterRequest$Outbound;
}

export function predictTTSDurationUsingCharacterRequestToJSON(
  predictTTSDurationUsingCharacterRequest:
    PredictTTSDurationUsingCharacterRequest,
): string {
  return JSON.stringify(
    PredictTTSDurationUsingCharacterRequest$outboundSchema.parse(
      predictTTSDurationUsingCharacterRequest,
    ),
  );
}

export function predictTTSDurationUsingCharacterRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PredictTTSDurationUsingCharacterRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PredictTTSDurationUsingCharacterRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PredictTTSDurationUsingCharacterRequest' from JSON`,
  );
}
