/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Request timeout error details
 */
export type RequestTimeoutErrorResponseMessage = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  error: string;
  /**
   * HTTP status code
   */
  statusCode: number;
};

/** @internal */
export const RequestTimeoutErrorResponseMessage$inboundSchema: z.ZodType<
  RequestTimeoutErrorResponseMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
  status_code: z.number(),
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
  });
});

/** @internal */
export type RequestTimeoutErrorResponseMessage$Outbound = {
  message: string;
  error: string;
  status_code: number;
};

/** @internal */
export const RequestTimeoutErrorResponseMessage$outboundSchema: z.ZodType<
  RequestTimeoutErrorResponseMessage$Outbound,
  z.ZodTypeDef,
  RequestTimeoutErrorResponseMessage
> = z.object({
  message: z.string(),
  error: z.string(),
  statusCode: z.number(),
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RequestTimeoutErrorResponseMessage$ {
  /** @deprecated use `RequestTimeoutErrorResponseMessage$inboundSchema` instead. */
  export const inboundSchema = RequestTimeoutErrorResponseMessage$inboundSchema;
  /** @deprecated use `RequestTimeoutErrorResponseMessage$outboundSchema` instead. */
  export const outboundSchema =
    RequestTimeoutErrorResponseMessage$outboundSchema;
  /** @deprecated use `RequestTimeoutErrorResponseMessage$Outbound` instead. */
  export type Outbound = RequestTimeoutErrorResponseMessage$Outbound;
}

export function requestTimeoutErrorResponseMessageToJSON(
  requestTimeoutErrorResponseMessage: RequestTimeoutErrorResponseMessage,
): string {
  return JSON.stringify(
    RequestTimeoutErrorResponseMessage$outboundSchema.parse(
      requestTimeoutErrorResponseMessage,
    ),
  );
}

export function requestTimeoutErrorResponseMessageFromJSON(
  jsonString: string,
): SafeParseResult<RequestTimeoutErrorResponseMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      RequestTimeoutErrorResponseMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RequestTimeoutErrorResponseMessage' from JSON`,
  );
}
