/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Too many requests error details
 */
export type TooManyRequestsErrorResponseMessage = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  error: string;
  /**
   * HTTP status code
   */
  statusCode: number;
};

/** @internal */
export const TooManyRequestsErrorResponseMessage$inboundSchema: z.ZodType<
  TooManyRequestsErrorResponseMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
  status_code: z.number(),
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
  });
});

/** @internal */
export type TooManyRequestsErrorResponseMessage$Outbound = {
  message: string;
  error: string;
  status_code: number;
};

/** @internal */
export const TooManyRequestsErrorResponseMessage$outboundSchema: z.ZodType<
  TooManyRequestsErrorResponseMessage$Outbound,
  z.ZodTypeDef,
  TooManyRequestsErrorResponseMessage
> = z.object({
  message: z.string(),
  error: z.string(),
  statusCode: z.number(),
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TooManyRequestsErrorResponseMessage$ {
  /** @deprecated use `TooManyRequestsErrorResponseMessage$inboundSchema` instead. */
  export const inboundSchema =
    TooManyRequestsErrorResponseMessage$inboundSchema;
  /** @deprecated use `TooManyRequestsErrorResponseMessage$outboundSchema` instead. */
  export const outboundSchema =
    TooManyRequestsErrorResponseMessage$outboundSchema;
  /** @deprecated use `TooManyRequestsErrorResponseMessage$Outbound` instead. */
  export type Outbound = TooManyRequestsErrorResponseMessage$Outbound;
}

export function tooManyRequestsErrorResponseMessageToJSON(
  tooManyRequestsErrorResponseMessage: TooManyRequestsErrorResponseMessage,
): string {
  return JSON.stringify(
    TooManyRequestsErrorResponseMessage$outboundSchema.parse(
      tooManyRequestsErrorResponseMessage,
    ),
  );
}

export function tooManyRequestsErrorResponseMessageFromJSON(
  jsonString: string,
): SafeParseResult<TooManyRequestsErrorResponseMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      TooManyRequestsErrorResponseMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TooManyRequestsErrorResponseMessage' from JSON`,
  );
}
