/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Unauthorized error details
 */
export type UnauthorizedErrorResponseMessage = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  error: string;
  /**
   * HTTP status code
   */
  statusCode: number;
};

/** @internal */
export const UnauthorizedErrorResponseMessage$inboundSchema: z.ZodType<
  UnauthorizedErrorResponseMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
  status_code: z.number(),
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
  });
});

/** @internal */
export type UnauthorizedErrorResponseMessage$Outbound = {
  message: string;
  error: string;
  status_code: number;
};

/** @internal */
export const UnauthorizedErrorResponseMessage$outboundSchema: z.ZodType<
  UnauthorizedErrorResponseMessage$Outbound,
  z.ZodTypeDef,
  UnauthorizedErrorResponseMessage
> = z.object({
  message: z.string(),
  error: z.string(),
  statusCode: z.number(),
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnauthorizedErrorResponseMessage$ {
  /** @deprecated use `UnauthorizedErrorResponseMessage$inboundSchema` instead. */
  export const inboundSchema = UnauthorizedErrorResponseMessage$inboundSchema;
  /** @deprecated use `UnauthorizedErrorResponseMessage$outboundSchema` instead. */
  export const outboundSchema = UnauthorizedErrorResponseMessage$outboundSchema;
  /** @deprecated use `UnauthorizedErrorResponseMessage$Outbound` instead. */
  export type Outbound = UnauthorizedErrorResponseMessage$Outbound;
}

export function unauthorizedErrorResponseMessageToJSON(
  unauthorizedErrorResponseMessage: UnauthorizedErrorResponseMessage,
): string {
  return JSON.stringify(
    UnauthorizedErrorResponseMessage$outboundSchema.parse(
      unauthorizedErrorResponseMessage,
    ),
  );
}

export function unauthorizedErrorResponseMessageFromJSON(
  jsonString: string,
): SafeParseResult<UnauthorizedErrorResponseMessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnauthorizedErrorResponseMessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnauthorizedErrorResponseMessage' from JSON`,
  );
}
