/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Unsupported media type error details
 */
export type UnsupportedMediaTypeErrorResponseMessage = {
  /**
   * Error message
   */
  message: string;
  /**
   * Error type
   */
  error: string;
  /**
   * HTTP status code
   */
  statusCode: number;
};

/** @internal */
export const UnsupportedMediaTypeErrorResponseMessage$inboundSchema: z.ZodType<
  UnsupportedMediaTypeErrorResponseMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  error: z.string(),
  status_code: z.number(),
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
  });
});

/** @internal */
export type UnsupportedMediaTypeErrorResponseMessage$Outbound = {
  message: string;
  error: string;
  status_code: number;
};

/** @internal */
export const UnsupportedMediaTypeErrorResponseMessage$outboundSchema: z.ZodType<
  UnsupportedMediaTypeErrorResponseMessage$Outbound,
  z.ZodTypeDef,
  UnsupportedMediaTypeErrorResponseMessage
> = z.object({
  message: z.string(),
  error: z.string(),
  statusCode: z.number(),
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnsupportedMediaTypeErrorResponseMessage$ {
  /** @deprecated use `UnsupportedMediaTypeErrorResponseMessage$inboundSchema` instead. */
  export const inboundSchema =
    UnsupportedMediaTypeErrorResponseMessage$inboundSchema;
  /** @deprecated use `UnsupportedMediaTypeErrorResponseMessage$outboundSchema` instead. */
  export const outboundSchema =
    UnsupportedMediaTypeErrorResponseMessage$outboundSchema;
  /** @deprecated use `UnsupportedMediaTypeErrorResponseMessage$Outbound` instead. */
  export type Outbound = UnsupportedMediaTypeErrorResponseMessage$Outbound;
}

export function unsupportedMediaTypeErrorResponseMessageToJSON(
  unsupportedMediaTypeErrorResponseMessage:
    UnsupportedMediaTypeErrorResponseMessage,
): string {
  return JSON.stringify(
    UnsupportedMediaTypeErrorResponseMessage$outboundSchema.parse(
      unsupportedMediaTypeErrorResponseMessage,
    ),
  );
}

export function unsupportedMediaTypeErrorResponseMessageFromJSON(
  jsonString: string,
): SafeParseResult<
  UnsupportedMediaTypeErrorResponseMessage,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UnsupportedMediaTypeErrorResponseMessage$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UnsupportedMediaTypeErrorResponseMessage' from JSON`,
  );
}
