/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UpdateCustomVoiceRequest = {
  /**
   * Name of the voice
   */
  name?: string | undefined;
  /**
   * Description of the voice
   */
  description?: string | undefined;
};

/** @internal */
export const UpdateCustomVoiceRequest$inboundSchema: z.ZodType<
  UpdateCustomVoiceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
});

/** @internal */
export type UpdateCustomVoiceRequest$Outbound = {
  name?: string | undefined;
  description?: string | undefined;
};

/** @internal */
export const UpdateCustomVoiceRequest$outboundSchema: z.ZodType<
  UpdateCustomVoiceRequest$Outbound,
  z.ZodTypeDef,
  UpdateCustomVoiceRequest
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCustomVoiceRequest$ {
  /** @deprecated use `UpdateCustomVoiceRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateCustomVoiceRequest$inboundSchema;
  /** @deprecated use `UpdateCustomVoiceRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateCustomVoiceRequest$outboundSchema;
  /** @deprecated use `UpdateCustomVoiceRequest$Outbound` instead. */
  export type Outbound = UpdateCustomVoiceRequest$Outbound;
}

export function updateCustomVoiceRequestToJSON(
  updateCustomVoiceRequest: UpdateCustomVoiceRequest,
): string {
  return JSON.stringify(
    UpdateCustomVoiceRequest$outboundSchema.parse(updateCustomVoiceRequest),
  );
}

export function updateCustomVoiceRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCustomVoiceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCustomVoiceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCustomVoiceRequest' from JSON`,
  );
}
