/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UpdateClonedVoiceResponse = {
  /**
   * Unique identifier for the voice
   */
  voiceId: string;
  /**
   * Name of the voice
   */
  name: string;
  /**
   * Description of the voice
   */
  description: string;
};

/** @internal */
export const UpdateClonedVoiceResponse$inboundSchema: z.ZodType<
  UpdateClonedVoiceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  voice_id: z.string(),
  name: z.string(),
  description: z.string(),
}).transform((v) => {
  return remap$(v, {
    "voice_id": "voiceId",
  });
});

/** @internal */
export type UpdateClonedVoiceResponse$Outbound = {
  voice_id: string;
  name: string;
  description: string;
};

/** @internal */
export const UpdateClonedVoiceResponse$outboundSchema: z.ZodType<
  UpdateClonedVoiceResponse$Outbound,
  z.ZodTypeDef,
  UpdateClonedVoiceResponse
> = z.object({
  voiceId: z.string(),
  name: z.string(),
  description: z.string(),
}).transform((v) => {
  return remap$(v, {
    voiceId: "voice_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateClonedVoiceResponse$ {
  /** @deprecated use `UpdateClonedVoiceResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateClonedVoiceResponse$inboundSchema;
  /** @deprecated use `UpdateClonedVoiceResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateClonedVoiceResponse$outboundSchema;
  /** @deprecated use `UpdateClonedVoiceResponse$Outbound` instead. */
  export type Outbound = UpdateClonedVoiceResponse$Outbound;
}

export function updateClonedVoiceResponseToJSON(
  updateClonedVoiceResponse: UpdateClonedVoiceResponse,
): string {
  return JSON.stringify(
    UpdateClonedVoiceResponse$outboundSchema.parse(updateClonedVoiceResponse),
  );
}

export function updateClonedVoiceResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateClonedVoiceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateClonedVoiceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateClonedVoiceResponse' from JSON`,
  );
}
