/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UpdateClonedVoiceRequest = {
  /**
   * Name of the voice
   */
  name?: string | undefined;
  /**
   * Description of the voice
   */
  description?: string | undefined;
};

/** @internal */
export const UpdateClonedVoiceRequest$inboundSchema: z.ZodType<
  UpdateClonedVoiceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
});

/** @internal */
export type UpdateClonedVoiceRequest$Outbound = {
  name?: string | undefined;
  description?: string | undefined;
};

/** @internal */
export const UpdateClonedVoiceRequest$outboundSchema: z.ZodType<
  UpdateClonedVoiceRequest$Outbound,
  z.ZodTypeDef,
  UpdateClonedVoiceRequest
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateClonedVoiceRequest$ {
  /** @deprecated use `UpdateClonedVoiceRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateClonedVoiceRequest$inboundSchema;
  /** @deprecated use `UpdateClonedVoiceRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateClonedVoiceRequest$outboundSchema;
  /** @deprecated use `UpdateClonedVoiceRequest$Outbound` instead. */
  export type Outbound = UpdateClonedVoiceRequest$Outbound;
}

export function updateClonedVoiceRequestToJSON(
  updateClonedVoiceRequest: UpdateClonedVoiceRequest,
): string {
  return JSON.stringify(
    UpdateClonedVoiceRequest$outboundSchema.parse(updateClonedVoiceRequest),
  );
}

export function updateClonedVoiceRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateClonedVoiceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateClonedVoiceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateClonedVoiceRequest' from JSON`,
  );
}
